import type { Metadata } from 'next'
  import Head from 'next/head'
import './globals.css'
import Script from 'next/script'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <Script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAucMUE36V0aM_aQugc_dOryrY3qo08UaA&libraries=places&callback=initMap"
        async
      />
      </head>
      <body  >{children}</body>
    </html>
  )
}
